[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
governance = "nWhEAJUqEqBiBzo8BKVfRK9aYMFCjLkjy9rhP2C6hia"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/vaibhav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
