[features]
seeds = false
skip-lint = false
[programs.localnet]
staking = "AFYuoTEtAiRQ3kDgwjPJQFZQrbNnmZ2FFGkq7Wm7piFo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/vaibhav/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
